name: Scraping para trazer meus badges

on:
  schedule:
    # Executa toda segunda-feira às 3h da manhã no fuso-horário UTC
    - cron: "0 3 * * 1"
jobs:
  update-readme:
    name: Atualizar README com meus badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: gustavo-potenza-coutinho
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Nova certificação obtida."
          CREDLY_SORT: POPULAR
          # BADGE_SIZE: 110x110
          NUMBER_LAST_BADGES: 48
        
